from src.utils import xyz_to_idx

GREATER_MATCH_COUNT = 10000
DEFAULT_MATCH_COUNT = 100
LESSER_MATCH_COUNT = 10

LAYER_COUNT = 3
ROW_COUNT = 3
COLUMN_COUNT = 3
TOTAL_COUNT = LAYER_COUNT * ROW_COUNT * COLUMN_COUNT
FORBIDDEN_INDEXES = [xyz_to_idx(1, 1, 1)]
MAX_MOVE_COUNT = TOTAL_COUNT - len(FORBIDDEN_INDEXES)
